-- Candados para datos reales:
-- 1) `version` en el ledger — escritura optimista: nadie pisa la captura de otro.
-- 2) `agrociclo_auditoria` — quién capturó qué y cuándo (rastro para soporte y pleitos de boletas).

alter table agrociclo_ledger add column if not exists version bigint not null default 0;

create table if not exists agrociclo_auditoria (
  id bigint generated by default as identity primary key,
  organizacion_id text not null,
  user_id text,
  email text,
  accion text not null,
  detalle jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);
create index if not exists agrociclo_auditoria_org_idx
  on agrociclo_auditoria (organizacion_id, creado_en desc);

alter table agrociclo_auditoria enable row level security;
