-- Entrar con celular (OTP por SMS) + candado anti-quema de saldo.
--
-- Las dos primeras columnas son del ESQUEMA DE BETTER AUTH (tabla "user"), así
-- que van camelCase y entre comillas como el resto de esa tabla — no snake_case
-- como las tablas propias de AgroCiclo. Las agrega el plugin `phoneNumber` de
-- Better Auth; ver src/lib/auth/server.ts.

alter table "user" add column if not exists "phoneNumber" text unique;
alter table "user" add column if not exists "phoneNumberVerified" boolean not null default false;

-- Candado anti-quema de saldo para el envío de códigos por SMS: un renglón por
-- intento de envío (exitoso o no), consultado por teléfono y por IP antes de
-- mandar el siguiente. Ver src/lib/auth/sms-throttle.server.ts.
create table if not exists agrociclo_sms_envio (
  id bigint generated by default as identity primary key,
  telefono text not null,
  ip text not null,
  enviado_en timestamptz not null default now()
);
create index if not exists agrociclo_sms_envio_telefono_idx on agrociclo_sms_envio (telefono, enviado_en desc);
create index if not exists agrociclo_sms_envio_ip_idx on agrociclo_sms_envio (ip, enviado_en desc);
